#!/bin/bash

# for last; do true; done
# filename=$(basename $last)

# case "$filename" in
#   *.pdf) binary=wkhtmltopdf ;;
#   *.png) binary=wkhtmltoimage ;;
#   *) exit;;
# esac

# "${binary[@]}" "$@"

ls /workdir
